# Site settings
title: Charles Zinn
email: charles@zinn.ca
description: >
  Personal website of a software engineering student at the University of Waterloo.
keywords:
  - blog
  - software
  - engineering
  - computer
  - science
  - waterloo
  - uw
  - lojban
  - esperanto
baseurl: ""
url: "http://charleszinn.ca"
github_username: czinn

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:title

# Build settings
markdown: kramdown

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false
  startings: [html, head, body]
sass:
  style: compressed
